### ISSUE TITLE
Directory case mismatch.

### ISSUE THREAD

**Issue by tlhonmey** [pvico/grbl32#6]
Git clone of the repo seems to name the directory "Src"
Makefile defines it as "src"
On case sensitive filesystems this causes the build to fail.

**Comment by pvico** [comment]
This is corrected now. Strange error, I'm on a Mac and it is a case sensitive OS. My local copy was indeed 'src'

**Comment by tlhonmey** [comment]
Well pulling the changes did report renaming Src to src, so it must not have just been me.  Probably fell afoul of some auto-capitalizer somewhere somehow.
